### ISSUE TITLE
How do you export the pt model to onnx?

### ISSUE THREAD

**Issue by dlavrantonis** [thnak/yolov7-rknn#1]
what exact params are you using? Can you upload the onnx model that is working for you?

**Comment by thnak** [comment]
> what exact params are you using? Can you upload the onnx model that is working for you?

for export .pt model to onnx model you can follow [this](https://github.com/thnak/yolov7-rknn/blob/main/getstart.ipynb)
and the [onnx](https://github.com/thnak/yolov7-rknn/blob/main/yolov7-tiny.onnx) model is woking here

**Comment by dlavrantonis** [comment]
thanks a ton! I just tried to convert the attached onnx to rknn. It works. Also tried the instructions on the notebook. They work too. I am able to export the official tiny yolo pt to onnx and then to rknn. FYI the exported rknns work on a real RK3588, I tried that as well

What fails is to try and use my own tiny yolov7 model. I followed the instructions on how to train. Training succeeds but trying to export the onnx file from the resulting pt model results in:


```
ONNX: Starting ONNX export with onnx 1.14.0
============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "export.py", line 294, in <module>
    onnx.utils.extract_model(input_path=f, output_path=f, input_names=start_points_2_break, output_names=end_points_2_break)
  File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 211, in extract_model
    extracted = e.extract_model(input_names, output_names)
  File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 167, in extract_model
    outputs = self._collect_new_outputs(output_names)
  File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 47, in _collect_new_outputs
    return self._collect_new_io_core(self.graph.output, names)  # type: ignore
  File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 37, in _collect_new_io_core
    new_io_tensors.append(self.vimap[name])
KeyError: '/model.77/im.1/Conv_output_0'
```

**Comment by thnak** [comment]
> thanks a ton! I just tried to convert the attached onnx to rknn. It works. Also tried the instructions on the notebook. They work too. I am able to export the official tiny yolo pt to onnx and then to rknn. FYI the exported rknns work on a real RK3588, I tried that as well
> 
> What fails is to try and use my own tiny yolov7 model. I followed the instructions on how to train. Training succeeds but trying to export the onnx file from the resulting pt model results in:
> 
> ```
> ONNX: Starting ONNX export with onnx 1.14.0
> ============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
> verbose: False, log level: Level.ERROR
> ======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================
> 
> Traceback (most recent call last):
>   File "export.py", line 294, in <module>
>     onnx.utils.extract_model(input_path=f, output_path=f, input_names=start_points_2_break, output_names=end_points_2_break)
>   File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 211, in extract_model
>     extracted = e.extract_model(input_names, output_names)
>   File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 167, in extract_model
>     outputs = self._collect_new_outputs(output_names)
>   File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 47, in _collect_new_outputs
>     return self._collect_new_io_core(self.graph.output, names)  # type: ignore
>   File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 37, in _collect_new_io_core
>     new_io_tensors.append(self.vimap[name])
> KeyError: '/model.77/im.1/Conv_output_0'
> ```

since your model has an IDetect class, you must re-parameter it before exporting any custom models. that will make the performance better
check out [this notebook](https://github.com/WongKinYiu/yolov7/blob/main/tools/reparameterization.ipynb) and I will update the export script to make sure no one gets this error again
thanks for your report

**Comment by thnak** [comment]
> 



> thanks a ton! I just tried to convert the attached onnx to rknn. It works. Also tried the instructions on the notebook. They work too. I am able to export the official tiny yolo pt to onnx and then to rknn. FYI the exported rknns work on a real RK3588, I tried that as well
> 
> What fails is to try and use my own tiny yolov7 model. I followed the instructions on how to train. Training succeeds but trying to export the onnx file from the resulting pt model results in:
> 
> ```
> ONNX: Starting ONNX export with onnx 1.14.0
> ============= Diagnostic Run torch.onnx.export version 2.0.0+cu117 =============
> verbose: False, log level: Level.ERROR
> ======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================
> 
> Traceback (most recent call last):
>   File "export.py", line 294, in <module>
>     onnx.utils.extract_model(input_path=f, output_path=f, input_names=start_points_2_break, output_names=end_points_2_break)
>   File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 211, in extract_model
>     extracted = e.extract_model(input_names, output_names)
>   File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 167, in extract_model
>     outputs = self._collect_new_outputs(output_names)
>   File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 47, in _collect_new_outputs
>     return self._collect_new_io_core(self.graph.output, names)  # type: ignore
>   File "/mnt500/GitHub/rockchip/yolov7/venv/lib/python3.8/site-packages/onnx/utils.py", line 37, in _collect_new_io_core
>     new_io_tensors.append(self.vimap[name])
> KeyError: '/model.77/im.1/Conv_output_0'
> ```

i have updated the export script. now you can try to export your custom model again without changes
 •ᴗ•

**Comment by dlavrantonis** [comment]
thank you for your kind help. Tried both ways, they seem to work. I'm struggling a bit with the post processing of the results -im using a slightly different image resolution- but ill figure this out.
